name: bloc_scope
description: The [bloc_scope] package helps you to easily cancel the futures and streams in case of BLOC or Cubit disposing.
repository: https://github.com/yaroslav13/bloc_scope
issue_tracker: https://github.com/yaroslav13/bloc_scope/issues

version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  async: 2.11.0
  bloc: 8.1.4
